apiVersion: funk.knative.dev/v1alpha1
kind: SDKInit
metadata:
  name: funk-nodejs-sdk
spec:
  steps:
    - name: "Creating funk directory"
      mkdir: "funks/{{.LowerFunkName}}" 
    # TODO: remove Dockerfile and .dockerignore once buildpacks integrated
    - name: "Create Dockerfile"
      template:
        source: "templates/funk/event_Dockerfile.tmpl"
        dest: "funks/{{.LowerFunkName}}/Dockerfile"
    - name: "Create .dockerignore"
      template:
        source: "templates/funk/dockerignore.tmpl"
        dest: "funks/{{.LowerFunkName}}/.dockerignore"    
    - name: "Create package.json"
      template:
        source: "templates/funk/event_package.json.tmpl"
        dest: "funks/{{.LowerFunkName}}/package.json"
    - name: "Create funk index.js"
      template:
        source: "templates/funk/event_index.js.tmpl"
        dest: "funks/{{.LowerFunkName}}/index.js"
    - name: "Create funk.js"
      template:
        source: "templates/funk/event_funk.js.tmpl"
        dest: "funks/{{.LowerFunkName}}/funk.js"
    - name: "Create service yaml"
      template:
        source: "templates/funk/service.yaml"
        dest: "config/{{.LowerFunkName}}_service.yaml"
    - name: "Create trigger yaml"
      template:
        source: "templates/funk/trigger.yaml"
        dest: "config/{{.LowerFunkName}}_trigger.yaml"

