apiVersion: funk.knative.dev/v1alpha1
kind: SDKInit
metadata:
  name: funk-nodejs-sdk
spec:
  steps:
    - name: "Creating funk directory"
      mkdir: "funks/{{.LowerFunkName}}" 
    # TODO: remove Dockerfile and .dockerignore once buildpacks integrated
    - name: "Create Dockerfile"
      template:
        source: "templates/funk/Dockerfile.tmpl"
        dest: "funks/{{.LowerFunkName}}/Dockerfile"
    - name: "Create .dockerignore"
      template:
        source: "templates/funk/dockerignore.tmpl"
        dest: "funks/{{.LowerFunkName}}/.dockerignore"    
    - name: "Create package.json"
      template:
        source: "templates/funk/package.json.tmpl"
        dest: "funks/{{.LowerFunkName}}/package.json"
    - name: "Create funk index.js"
      template:
        source: "templates/funk/index.js.tmpl"
        dest: "funks/{{.LowerFunkName}}/index.js"              
    - name: "Create service yaml"
      template:
        source: "templates/funk/service.yaml"
        dest: "config/{{.LowerFunkName}}_service.yaml"
